version: "3.9"
services:
  crackDetection:
    image: bhpchen/crackdetection
    container_name: crackDetection
    ports:
      - "5000:5000"
    volumes:
      - ./detect.py:/usr/src/app/detect.py
      - ./cut_video.py:/usr/src/app/cut_video.py
      - ./app.py:/usr/src/app/app.py
